# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b10acbc64d7cbf27b6268271e1afcecb44baf5803971303024c6e6cec18277b8abbc0feef62f9234ce338385826fc2972073039c48c66cf086bf4aee90db605

test:
  secret_key_base: 3d7e445c9661d81813b6167d45321cd8e9861c80cfea6cc6d9dc6f4bfc116189c4d69dadb7b3dfa00737bed46ae7adbd7e94cd2287a8775b82e8134b255616ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
